### PR TITLE
Performance Tests - RAM disk

### PR DESCRIPTION
**Pull request by mikicho**
I created a simple DB performance test that inserts 100 new rows into the database through the API.
From what I see, with [non-durable settings](https://github.com/testjavascript/integration-tests-a-z/blob/master/example-application/test/docker-compose.yml#L5) the performance difference, between SSD and ram, is neglectable (if any). I tested it also with big tables (500k rows), the insert performance stays the same.
In durable settings, the `ramdisk` is faster in about 30%-40% than SSD.

My only concern is that our schema is too simplistic, and doesn't have unique keys which will cause more reads on insert and may give an advantage for the `ramdisk`

My conclusion from this little research is that `ramdisk` doesn't give a real benefit and we should recommend it only for CI environments because it's so simple (one line), so why not?

I opened this PR to show you what I did and how I got those numbers so maybe you'll find that I did something wrong during my testing, and therefore my conclusion is wrong.

In addition, I:
* Added an `nvm` file so all of us will use and test with the same node version
* Added package-lock` file so all of us will use and tests with the same package's version.
* Small fix for `docker-compose`

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@mikicho Working toward some big milestone on Sunday afternoon, plan to review by EOD Sunday

**Review by goldbergyoni — APPROVED** [review]
@mikicho  I would merge what we have now, a good enough performance analysis cycle. We will revisit it in the future. Consider adding your great finding in a dedicated recipe readme.

**Comment by goldbergyoni** [comment]
@mikicho Jest parallelizes tests by files, if you want to benefit multi-process you have to create multiple files, at least 4. Do we split here the tests across files? This might change the results

**Comment by mikicho** [comment]
@goldbergyoni how it will improve database performance? (we're talking here about DB RAM only performance improvement. other improvements have another ticket)

**Comment by mikicho** [comment]
added readme

**Comment by goldbergyoni** [comment]
> @goldbergyoni how it will improve database performance? (we're talking here about DB RAM only performance improvement. other improvements have another ticket)
> 
> Update: Now I see that the name `performance` is misleading. maybe we should add to this recipe other performance improvements as well but it's out of the scope of this PR

@mikicho We're measuring DB optimizations, as part of measuring we want to utilize them. The more stress we put on DB, the more the optimizations shine. Makes sense or do I miss something?

**Comment by mikicho** [comment]
@goldbergyoni I see. so you want multiple test files in the recipe which have this parameterized test?
I'll check it... but I don't think it will do any better. I think the non-durable settings reduce the I/O to almost zero and make it neglectable

**Comment by mikicho** [comment]
@goldbergyoni tested it.. didn't see any improvement between ramdisk and SSD with non-durable settings

**Pull request merged**
