### PR TITLE
added contributing file/39

### PR DESCRIPTION
**Pull request by mikicho**

### CODE REVIEW

**Review by goldbergyoni — CHANGES_REQUESTED** [review]
It's very professional and detailed and I like it.

At the same time it's too 'Ashkenazi' 😅, We the Tunisian people use to warmly welcome people to our house. Now seriously, I would just add one first paragraph that motivates people to join us, something like?

So you want to join our family, people who appreciate and love testing? 💜  You might get addiced and dramatically push your testing skills, you've been warned. Still interesting? Keep reading

**Comment by mikicho** [comment]
@goldbergyoni lol 
Done

**Review by goldbergyoni — COMMENTED** [review]
LGTM

**Review by goldbergyoni — APPROVED** [review]
LGTM

**Pull request merged**
